registry:
  restart: always
  image: registry:2
  ports:
    - 6000:5000
  environment:
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
  volumes:
    - ./data:/var/lib/registry
    - ./certs:/certs
    - ./auth:/auth
